services:
  go:
    image: golang:1.23
    build:
      context: go
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - ./go:/app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - tamemie-network

  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - ./etc/mysql/dbdata:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - tamemie-network

networks:
  tamemie-network:
    driver: bridge
